### ISSUE TITLE
Just FYI

### ISSUE THREAD

**Issue by Juanlu001** [Horta/ncephes#1]
I stumbled upon this project coming from a numba issue and was surprised that we had the same idea within some months :)

https://github.com/poliastro/pycephes

I implemented this for my own needs (an hypergeometric function) and ran out of time to maintain it, but I will leave you a link here in case it's interesting for you.

Cheers!

**Comment by Horta** [comment]
Hi Juan. Thank you for the message =)
Your project actually inspired me to finally do this =) Cephes is a library that I have been using a lot but there is no decent wrapper around it for Python purposes (Numba, Cython, and standard Python call). 

First I thought about contributing to pycephes but I wanted to wrapping something more automatic. For example, [here](https://raw.githubusercontent.com/Horta/ncephes/master/update_source.py) I update the folder containing cephes with the original sources, apply patches, and do some housekeeping. (even though cephes source is not modified anymore, I just wanted something repeatable in case I want to reestructure something in the future). And [here](https://raw.githubusercontent.com/Horta/ncephes/master/cprob_build.py) I compile and export cprob functions automatically.

You are very welcomed to propose any changes, of course =) My goal is: export Cephes to Python, Numba, Cython, and [C/C++](https://raw.githubusercontent.com/Horta/ncephes/master/ncephes/lib.py), and [document it](http://ncephes.readthedocs.org/).

**Comment by Juanlu001** [comment]
The idea of having automatic compilation of the functions is great! I am glad that my prototype inspired you to kick off nCephes :blush: Good luck with this project and I hope you success and we start seeing more CFFI + numba + Python integrations!
